experiment: l200cfg01

runlist:
- l200-p03-r000-phy
# - l200-p03-r001-phy
# - l200-p03-r002-phy
# - l200-p03-r005-phy
# - l200-p04-r000-phy
# - l200-p04-r001-phy

simlist: all

make_tiers:
  - vtx
  - stp
  - hit
  
benchmark:
  enabled: false
  n_primaries:
    stp: 5000
    vtx: 10000

paths:
  benchmarks: $_/generated/benchmarks
  log: $_/generated/log

  metadata: $_/inputs
  config: $_/inputs/simprod/config
  optical_maps:
    fiber: $_/inputs/simprod/l200a-optical-map-fiber.lh5
    lar: /dvs_ro/cfs/cdirs/m2676/sims/optmap/l200cfg01/l200cfg01-optmap-v2.lh5
    pen: $_/inputs/simprod/l200a-optical-map-pen.lh5

  genconfig: $_/generated/config
  macros: $_/generated/macros
  geom: $_/generated/geom
  dtmaps: $_/generated/dtmaps
  tier_evt: $_/generated/tier/evt
  tier_hit: $_/generated/tier/hit
  tier_pdf: $_/generated/tier/pdf
  tier_stp: $_/generated/tier/stp
  tier_vtx: $_/generated/tier/vtx
  pdf_releases: $_/generated/releases
  plots: $_/generated/plots
#

precompile_pkg:
   - lgdo
   - matplotlib
   - reboost
   - legendhpges
   - legendoptics
   - pygeomtools
#
# runcmd:
#   remage: apptainer run --cleanenv /home/gipert/sw/apptainer/remage_latest.sif
