/RMG/Manager/Randomization/Seed {SEED}

/RMG/Geometry/RegisterDetectorsFromGDML Germanium
/RMG/Geometry/RegisterDetectorsFromGDML Scintillator

# name tables with ntuple
/RMG/Output/NtupleUseVolumeName True

/run/initialize

# discard events without Germanium energy
/RMG/Output/Germanium/EdepCutLow 0

# store everything as single
/RMG/Output/Germanium/StoreSinglePrecisionPosition
/RMG/Output/Germanium/StoreSinglePrecisionEnergy
/RMG/Output/Scintillator/StoreSinglePrecisionPosition
/RMG/Output/Scintillator/StoreSinglePrecisionEnergy
/RMG/Output/Vertex/StoreSinglePrecisionPosition

# physics options
/RMG/Processes/EnableGammaAngularCorrelation

# store trackid
/RMG/Output/Germanium/StoreTrackID true
/RMG/Output/Scintillator/StoreTrackID true

$GENERATOR

$CONFINEMENT

/run/beamOn {N_EVENTS}
